### ISSUE TITLE
installation on Ha

### ISSUE THREAD

**Issue by wifi75** [maxill1/ialarm-mqtt#11]
hello but it is possible install on HA?

**Comment by maxill1** [comment]
Do you mean directly in Home Assistant via HassOS addon?

This is available on docker, like any HassOS add-ons, but I haven't checked how to formally make an add-on.

You can install it via docker https://github.com/maxill1/ialarm-mqtt#running-with-docker-image

Or nodejs https://github.com/maxill1/ialarm-mqtt#running-with-nodejs
