### ISSUE TITLE
Direct integration with Home Assistant?

### ISSUE THREAD

**Issue by Stinocon** [maxill1/ialarm-mqtt#12]
No real issues, just a question.... Any plans to create a more convenient integration directly into Home Assistant? 
A HACS plugin or a real Add-On? That would be great! 

Thanks

**Comment by maxill1** [comment]
I should look into home assistant add-on docs to check how to do it, but since those are docker based I think it could be done somehow.

I really can't make an HACS plugin, cause this is not a component and it's not python based, sorry.

If you want to use a native home assistant component you should check the wonderful work made by RyuzakiKK https://github.com/RyuzakiKK/pyialarm

**Comment by Stinocon** [comment]
If I am not mistaken pyialarm is the basis of the plugin that was later discontinued by Home Assistant.
I'm already using just that by simply importing it into my custom_components folder and it works perfectly BUT your version would also allow me to know the status of each individual sensor via MQTT which would be a nice game changer.

Hence the request for a custom add-on :D 

Obviously I could do the same thing with Node-Red but I don't find much sense to set up Node-Red only for the states of the sensors of the alarm (experience already done, but I dismissed Node-Red with the arrival of blueprints)

If by chance you want to go the way of the custom addon I can obviously be a tester.

**Comment by maxill1** [comment]
Actually ialarm-mqtt already support home assistant via mqtt autodiscovery
(just like you I wanted to use less node-red). Just use docker or install
via nodejs and you should find entities in you Home assistant instance. To
simplify the installation process for end users I will look into add-ons as
soon I have some spare time, but can't make promises, I'm pretty busy right
now, sorry.

Il Dom 31 Gen 2021, 10:59 Stefano <notifications@github.com> ha scritto:

**Comment by wifi75** [comment]
@Stinocon  Hello how I can installa ialarm-mqtton HA?

**Comment by wifi75** [comment]
> Se non sbaglio, pyialarm è la base del plugin che è stato successivamente interrotto da Home Assistant.
> Lo sto già usando semplicemente importandolo nella mia cartella custom_components e funziona perfettamente MA la tua versione mi permetterebbe anche di conoscere lo stato di ogni singolo sensore tramite MQTT, il che sarebbe un bel punto di svolta.
> 
> Da qui la richiesta di un add-on personalizzato: D
> 
> Ovviamente potrei fare la stessa cosa con Node-Red ma non trovo molto senso impostare Node-Red solo per gli stati dei sensori di allarme (esperienza già fatta, ma ho congedato Node-Red con l'arrivo di progetti)
> 
> Se per caso vuoi seguire la strada dell'addon personalizzato posso ovviamente essere un tester.

Hello, how i can Install on HA?

**Comment by maxill1** [comment]
@wifi75 Ti riferisci all'addon che deriva da pyialarm o ialarm-mqtt?

> > Se non sbaglio, pyialarm è la base del plugin che è stato successivamente interrotto da Home Assistant.
> > Lo sto già usando semplicemente importandolo nella mia cartella custom_components e funziona perfettamente MA la tua versione mi permetterebbe anche di conoscere lo stato di ogni singolo sensore tramite MQTT, il che sarebbe un bel punto di svolta.
> > Da qui la richiesta di un add-on personalizzato: D
> > Ovviamente potrei fare la stessa cosa con Node-Red ma non trovo molto senso impostare Node-Red solo per gli stati dei sensori di allarme (esperienza già fatta, ma ho congedato Node-Red con l'arrivo di progetti)
> > Se per caso vuoi seguire la strada dell'addon personalizzato posso ovviamente essere un tester.
> 
> Hello, how i can Install on HA?

please stay in topic: if you need support for pyalarm continue on the issue you opened on [RyuzakiKK/pyialarm](https://github.com/RyuzakiKK/pyialarm/issues/4)

**Comment by maxill1** [comment]
Home Assistant Add-On available: https://github.com/maxill1/addons

see also: https://github.com/indomus/forum/discussions/239
