### ISSUE TITLE
ialarm-mqtt on HA

### ISSUE THREAD

**Issue by wifi75** [maxill1/ialarm-mqtt#16]
Hello I copy ialarm-mqtt on custom_componets, I configured the config.json file, and then what should I do to make HA recognize the component?

**Comment by maxill1** [comment]
You are using it as a custom component...but this is and add-on!

Just follow the [Add-on installation guide](https://github.com/maxill1/ialarm-mqtt/wiki/Installation#running-with-home-assistant-add-on)
