### ISSUE TITLE
Mqttthing configuration support

### ISSUE THREAD

**Issue by mrMiimo** [maxill1/ialarm-mqtt#17]
Hi, 
I have updated to the latest version and set port 18034. 
When I set a state in the alarm, I find "ERR | 00" in the log, is this normal?  
Anyway at the moment everything seems to be work fine…

```log Disconnecting from 192.168.178.33:18034
{
  commandNames: [ 'SetAlarmStatus' ],
  commandArgs: [ '1' ],
  data: { SetAlarmStatus: { event: 'response', response: [Object] } }
}
{
  commandNames: [ 'SetAlarmStatus' ],
  commandArgs: [ '1' ],
  data: { SetAlarmStatus: { event: 'response', response: [Object] } }
}
Connected to 192.168.178.33:18034
Connected to 192.168.178.33:18034
Disconnecting from 192.168.178.33:18034
Disconnecting from 192.168.178.33:18034
{
  status: { event: 'response', response: { Root: [Object], Err: 'ERR|00' } },
  zones: undefined
}
error
Caching ialarm/alarm/state until Sat Oct 09 2021 12:26:47 GMT+0000 (Coordinated Universal Time)
sending topic 'ialarm/alarm/state' : {"event":"response","response":{"Root":{"Pair":{"Client":{"Err":{}}}},"Err":"ERR|00"}}
No zone found to publish
Connected to 192.168.178.33:18034
Disconnecting from 192.168.178.33:18034
```

**Comment by maxill1** [comment]
Hi the "ERR" response error is related to a known issue: https://github.com/maxill1/node-ialarm/issues/7

I don't know much about mqttthing but some commit ago I changed some of the default device classes.
You can configure them by overriding specific zones:
https://github.com/maxill1/ialarm-mqtt/wiki/Configuration#specific-zone-config

**Comment by mrMiimo** [comment]
thanks for the feedback.
I configured the specific zones, but it didn't work, they continue (doors and motion sensor) to be always active ...
Maybe I do a rollback of the docker compose 😞

**Comment by maxill1** [comment]
Sorry now I get the problem: you are saying that getStatusActive reports "active" while it should not be.

Since TCP implementation (0.8.0) changed the default status to 1, your getMotionDetected topic is getting bad readings.

You can change your configuration like this:
```json
          "getMotionDetected": {
                "topic": "ialarm/sensors/state",
                "apply": "if (JSON.parse(message)[1].status > 1) return 1; else return 0;"
            },
```

keep in mind that using "status" greater than 1 may results in "motion detection" in any of this case:
- bypass (status=5)
- fault (status=9)
- bypassed and fault (status=13)
- low battery (status TBD, but still greater than 1!)
- alarm (status TBD, but still greater than 1!)
- wirelessLoss (status TBD, but still greater than 1!)

**Comment by mrMiimo** [comment]
Thanks for the list of all the values that can take "state", it is clarifying.

I took a test, it works! 👍🏼
But I also had to change the reading order of the string. Although I have specified the hotspots with: `"zones": [7,33,34,35,36,38,39,40]`, it now lists all 40 zones.

Does the option that specify active zones still work?

```
"server" : {
        "host": "192.168.178.33",
        "port": "18034",
        "username": "XXXXX",
        "password": "XXXX",
	"hadiscovery": {"enabled" : false},
        "zones": [7,33,34,35,36,38,39,40],
        "polling" : {
            "status" : 3500,
            "events" : 400000
        }
```

**Comment by maxill1** [comment]
no no, it's a bug! confirmed. WIP.

**Comment by maxill1** [comment]
> "Zones", seems to work! Thanks! I keep seeing in the logs:
> 
> `[Esterno Soggiorno Giardino] Ignoring invalid value [true] for Status Fault - not an integer`
> 
> Maybe setting mqttthing this way works.
> 
> ```
> "getStatusLowBattery": {
>                    "topic": "ialarm/sensors/state",
>                    "apply": "if (JSON.parse (message) [7].lowbat = 'true') return 1; else return 0;"
>                }
> ```
> 
> It is difficult to simulate "lowbat", what do you think?

you are missing one "=" in your if statement:

```json
"getStatusLowBattery": {
     "topic": "ialarm/sensors/state",
     "apply": "if (JSON.parse (message) [7].lowbat == 'true') return 1; else return 0;"
 }

```

to simulate a lowbat you can try like this:
- install [MQTT explorer](http://mqtt-explorer.com/) connect to the broker and copy a ialarm/sensors/state payload to a file editor (notepad++, visual studio code, etc)
- edit one of your sensor setting lowbat : true
- on ialarm-mqtt increment the status polling to a very large value (60-120 seconds) and restart the container and wait for startup
- publish the payload you just edited and mqttthing should pickup the values.

**Comment by maxill1** [comment]
dopo lavoro verifico, probabilmente è un bug. è stato cambiato molto dalla versione scraper, serve pazienza.

Per chiarezza, tu che centrale hai? Vorrei censire un po i modelli perchè altri utenti con "casasicura" hanno molti problemi di connessione.

**Comment by mrMiimo** [comment]
Ciao Luca, ho visto che hai rilasciato un'aggiornamento. Conviene farlo anche a me? per caso risolve la questione sopra?
Grazie mille.

**Comment by maxill1** [comment]
puoi anche non aggiornare, risolve altre problematiche.

La tua secondo me è solo di configurazione della funzione "apply". Dalla documentazione di [mqttthing per i motion-sensor](https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Accessories.md#motion-sensor) dice che puoi trattarli come boolean oppure integer  usando "integerValue": true.

Ma se togli "integerValue": true da mqttthing, togli "sensorOn" : "1",    "sensorOff" : "0" da ialarm-mqtt e torni a usare solo boolean come nell'[esempio della documentazione di mqttthing](https://github.com/arachnetech/homebridge-mqttthing/wiki/Tested-Configurations#ikea-tradfri-motion-sensor)?

```javascript
{
    "accessory": "mqttthing",
    "type": "motionSensor",
    "name": "Esterno Soggiorno Giardino",
    "url": "mqtt://XXXXXX:1883",
    "username": "XXXXXX",
    "password": "XXXXX",
    "caption": "Zona 33: Sensore Esterno Soggiorno",
    "topics": {
        "getMotionDetected": {
            "topic": "ialarm/sensors/state",
            "apply": "return JSON.parse(message)[32].status > 1;"
        },
        "getStatusActive": {
            "topic": "ialarm/sensors/state",
            "apply": "return JSON.parse(message)[32].ok;"
        },
        "getStatusFault": {
            "topic": "ialarm/sensors/state",
            "apply": "return JSON.parse(message)[32].fault;"
        },
        "getStatusLowBattery": {
            "topic": "ialarm/sensors/state",
            "apply": "return JSON.parse(message)[32].lowbat;"
        }
    }
}
```

**Comment by mrMiimo** [comment]
solo adesso sono riuscito a provare.
Ho variato la configurazione come mi hai suggerito però non ha cambiato niente... continuo a ricevere il messaggio:
`[1/13/2022, 4:08:29 PM] [Esterno Soggiorno Giardino] Ignoring invalid value [false] for Status Fault - not an integer`

Non saprei cosa altro provare.. :\
