### ISSUE TITLE
TCP version generic error report

### ISSUE THREAD

**Issue by Nik71git** [maxill1/ialarm-mqtt#18]
Hi,
addon is configured properly and mqtt broker also. 
TCP port is 18034, ip address is correct, user and password too...
Below the log:

Error: Meian socket timed out after 30000 ms (your address/port may be wrong or the alarm may be hanging. Try connecting with your Android Phone, if not working either reboot the alarm and try again.)
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/ialarm/src/meian-socket.js:214:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
ialarm/alarm/error - not publishing...unchanged
Connection closed
Disconnecting from 192.168.1.6:18034

**Comment by Nik71git** [comment]
da app e da pagina web funziona, il settaggio è corretto con la porta 18034 (si legge anche dalla pagina di configurazione del cloud). Con web scraping funzionava perfettamente, ho provato con fing ma mi vede solo la porta http ed ftp

**Comment by Nik71git** [comment]
per la cronaca ho una siqura web di casasicura.it (Meian)

**Comment by maxill1** [comment]
> Lo avevo eliminato, ho appena provato a rimetterlo su e non riesce a connettersi alla centrale…. Ma andava….giuro che andava…

Era una domanda a trabocchetto! Mi è capitato uguale mentre testavo la versione TCP, a volte per motivi a me sconosciuti la centrale si impalla e non risponde più al suo stesso protocollo. Nel mio caso giustamente si è impallata mentre mandavo messaggi sbagliati, nel tuo caso non saprei. Cmq fai un reboot da web e dovrebbe sistemarsi.

**Comment by gideonklein** [comment]
A me non funziona più niente. Si, eccetto la lentezza web scraping funzionava tutto

**Comment by maxill1** [comment]
l'IP con il 47 è sicuramente un Middleware di meian/casa sicura/antifurto365 che serve a raggiungere l'antifurto anche dietro rete privata (Nat, routing, etc).

@gideonklein a te il plug-in di homeassistant in python funziona?

Mi mandate un log più lungo relativo al timeout? Vorrei capire se è relativo alla connessione alla porta, alla login o a un comando.

**Comment by gideonklein** [comment]
Ciao Grazie, il plug-in in python sarebbe con la porta 80? Se è questo non funziona più con la nuova versione. Ti mando volentieri il log ma dove lo trovo? Scusa le domande per voi scontate

**Comment by gideonklein** [comment]
va bene ho trovato:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:15:37] INFO: Passing /data/options.json to ialarm-mqtt@ 0.8.0 with node-ialarm@ 0.4.1
Found arg --hassos with value /data/options.json
Trying to merge HASSOS options file (/data/options.json) with default config.json
Config.json value not specified on /data/options.json using default '2' on ["hadiscovery","topics","alarm_qos"]
Config.json value not specified on /data/options.json using default '0' on ["hadiscovery","topics","sensors_qos"]
Starting up...
Status polling every  30000  ms
Events polling every  10000  ms
Loading zone cache...
Disconnecting from 192.168.3.136:18034
error Meian socket timed out after 30000 ms (your address/port may be wrong or the alarm may be hanging. Try connecting with your Android Phone, if not working either reboot the alarm and try again.)
Error: Meian socket timed out after 30000 ms (your address/port may be wrong or the alarm may be hanging. Try connecting with your Android Phone, if not working either reboot the alarm and try again.)
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/ialarm/src/meian-socket.js:214:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
ialarm/alarm/error - error publishing...not connected
Connection closed
[cmd] /run.sh exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by Nik71git** [comment]
Ecco il mio log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:17:39] INFO: Passing /data/options.json to ialarm-mqtt@ 0.8.0 with node-ialarm@ 0.4.1
Found arg --hassos with value /data/options.json
Trying to merge HASSOS options file (/data/options.json) with default config.json
Config.json value not specified on /data/options.json using default '2' on ["hadiscovery","topics","alarm_qos"]
Config.json value not specified on /data/options.json using default '0' on ["hadiscovery","topics","sensors_qos"]
Starting up...
Status polling every  30000  ms
Events polling every  10000  ms
Loading zone cache...
Disconnecting from 192.168.1.6:18034
error Meian socket timed out after 30000 ms (your address/port may be wrong or the alarm may be hanging. Try connecting with your Android Phone, if not working either reboot the alarm and try again.)
Error: Meian socket timed out after 30000 ms (your address/port may be wrong or the alarm may be hanging. Try connecting with your Android Phone, if not working either reboot the alarm and try again.)
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/ialarm/src/meian-socket.js:214:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
ialarm/alarm/error - error publishing...not connected
Connection closed
[cmd] /run.sh exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by gideonklein** [comment]
Ma io no ne ho plugin! Forse ti riferisci a quello che si crea su mqtt?
![Cattura](https://user-images.githubusercontent.com/79428290/136711997-228bacb5-8e5c-46e6-9c61-9023941619ee.PNG)

**Comment by gideonklein** [comment]
Ho sbagliato, scusate
![Cattura2](https://user-images.githubusercontent.com/79428290/136712068-474d21f0-f932-4102-a6c4-0e4fa79656ea.PNG)

**Comment by gideonklein** [comment]
Installato, ho resettato la centrale e mi ha connesso

**Comment by gideonklein** [comment]
Purtroppo non sono capace con Telnet, probabilmente Nik71git lo sa fare

**Comment by gideonklein** [comment]
maxill1 , funziona ora armo e disarmo con entrambi, ma devo provare i sensori perchè l'integrazioni fa fare solo armo e disarmo

**Comment by maxill1** [comment]
L'integrazione è un altra cosa, corretto che faccia solo arm/disarm... è proprio un plugin scritto da un altra persona.

Cmq ora dal log vedo che ialarm-mqtt legge e pubblica i sensori e le altre entità. Dovresti trovare appunto sotto le entità di home assistant.

**Comment by Nik71git** [comment]
![Screenshot_20211010-224157](https://user-images.githubusercontent.com/61212989/136712491-1d1f88b9-8a73-4931-9152-35b1e9a1d58a.png)
Con Telnet mi collego (sto provando da Cell... sono in 🚽)

**Comment by gideonklein** [comment]
ALlora, ora funziona armo e disarmo con entrambi la il sensore last event ci impiega più di 30 secondi. 
Funzionano anche gli switch che però sono rilevati dal sensore last event in 1 secondo.
I sensori, probabilmente funzionano ma li devo provare. Intanto posso provare le finestre e vi faccio sapere

**Comment by gideonklein** [comment]
allora ho scoperto cose che hanno dell'incredibile :)
Praticamente a parte il ritardo di 1 minuto che proverò a correggere con il polling, ci deve essere un'errore nei numeri delle zone nell'addon. quando ho aperto la finestra bagno che è la zona 12 mi si è attivato il sensore pir che è zona 13 e quando ho aperto la finestra cucina che è zona 8 mi si è attivato il sensore pir che è la zona 9 ma il sensore last event li ha visti corretti. Forse i sensori binari devono partire dal numero zero?

**Comment by Nik71git** [comment]
![Screenshot_20211010-230728](https://user-images.githubusercontent.com/61212989/136713019-02b54fc7-2cf3-48c8-b551-a2caa84ffbbd.png)
@maxill1 ti allego lo screenshot della mia situazione, effettivamente si collega in qualche modo dopo il riavvio della centrale (da entità non disponibili diventano disponibili) ma rileva uno stato non vero, in questo momento è armato e i sensori sono tutti chiusi. Non so dove vada a leggere questi stati. Arm e disarm non funzionano comunque.

**Comment by gideonklein** [comment]
Per quello che vedo io ci sono continue connessioni e disconnessioni, è normale?

`Disconnecting from 192.168.3.136:18034
Caching ialarm/alarm/event until Sun Oct 10 2021 23:35:53 GMT+0200 (Central European Summer Time)
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Caching ialarm/alarm/availability until Sun Oct 10 2021 23:36:09 GMT+0200 (Central European Summer Time)
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
Caching ialarm/alarm/state until Sun Oct 10 2021 23:36:10 GMT+0200 (Central European Summer Time)
sending topic 'ialarm/alarm/state' : disarmed
Caching ialarm/sensors/state until Sun Oct 10 2021 23:36:10 GMT+0200 (Central European Summer Time)
sending topic 'ialarm/sensors/state' : Array of 40 elements
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
ialarm/alarm/availability - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/state - not publishing...unchanged
ialarm/sensors/state - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
Caching ialarm/alarm/event until Sun Oct 10 2021 23:36:53 GMT+0200 (Central European Summer Time)
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Caching ialarm/alarm/availability until Sun Oct 10 2021 23:37:10 GMT+0200 (Central European Summer Time)
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/state - not publishing...unchanged
ialarm/sensors/state - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
ialarm/alarm/availability - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
Caching ialarm/alarm/state until Sun Oct 10 2021 23:37:40 GMT+0200 (Central European Summer Time)
sending topic 'ialarm/alarm/state' : disarmed
Caching ialarm/sensors/state until Sun Oct 10 2021 23:37:40 GMT+0200 (Central European Summer Time)
sending topic 'ialarm/sensors/state' : Array of 40 elements
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
Caching ialarm/alarm/event until Sun Oct 10 2021 23:37:59 GMT+0200 (Central European Summer Time)
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged
Caching ialarm/alarm/availability until Sun Oct 10 2021 23:38:10 GMT+0200 (Central European Summer Time)
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/state - not publishing...unchanged
ialarm/sensors/state - not publishing...unchanged
Connected to 192.168.3.136:18034
Disconnecting from 192.168.3.136:18034
ialarm/alarm/event - not publishing...unchanged`

**Comment by gideonklein** [comment]
@maxill1 grazie. Ma ancora problemi
- Mi confermi intanto che posso disinstallare l'integrazione antifurto365? Oppure la devo lasciare?
- Armo, disarmo e bypass funzionano ma i sensori ci sono i seguenti errori
- - Porte me li rileva solo last event
- - Il sensore acqua (zona 5) me lo rileva correttamente last event ma si attiva il sensore gas (zona 6) praticamente si attivano i sensori una zona superiore, il 6 al posto del 5, così come ieri il 9 al posto dell'8, etc
Allego lo screen
![Inked1633944132649_LI](https://user-images.githubusercontent.com/79428290/136766560-de4d4c6b-b587-452c-a743-fa48b05fb09c.jpg)

**Comment by gideonklein** [comment]
Ho disinstallato l'integrazione alarm360 ma non funziona più niente

**Comment by Nik71git** [comment]
io continuo ad avere uno strano comportamento... ad ogni riavvio di centrale (anche spenta fisicamente e riaccesa...) o ad ogni riavvio dell'addon tutte le entità sono non disponibili, solo se faccio riavviare il broker mqtt allora mi vede la centrale ma con uno stato dei sensori assolutamente non veritiero. Non riesco ad armare/disarmare, i sensori non cambiano di stato, quelli che sono open rimangono open, quelli che sono closed rimangono closed.... Mi viene in mente il retain a true (posso impostare false?) e QoS che è a 0 (io metterei almeno ad 1 ma come faccio??? come gestisco i parametri mqtt nell'addon?

**Comment by maxill1** [comment]
@Nik71git per capire cosa succede prova a verificare cosa arriva al broker mqtt. Ti consiglio di provare MQTT explorer e navigare fino al topic ialarm/alarm/state per capire se arriva o meno il messaggio. Se possibile fallo con l'ultima versione disponibile dell'addon (al momento 2.0.4).

![image](https://user-images.githubusercontent.com/367042/137224571-98dec035-aeb8-4a6e-a026-911941cce91f.png)

**Comment by Nik71git** [comment]
@maxill1 
![image](https://user-images.githubusercontent.com/61212989/137365793-fe497db2-a762-4cb4-9861-42b7392c35b2.png)
vede il comando disarmed (set) ma non lo implementa (state)....
idee ??

**Comment by Nik71git** [comment]
![image](https://user-images.githubusercontent.com/61212989/137371239-7fac377e-8c2f-4ad9-9fd7-5bbd2013fa72.png)
questo è il log quando riavvio l'addon

**Comment by Nik71git** [comment]
![image](https://user-images.githubusercontent.com/61212989/137579662-b9c82ace-1bbb-4406-beb4-0cec16f25f79.png)
anche con il plugin di ryuzakikk non si connette più (eppure si connetteva)... 
Raggiungo perfettamente la web UI della centrale via browser e via app (cloud) ed esegue tutti i comandi senza alcun problema. Sembra quasi che la porta 18034 dia problemi...

**Comment by gideonklein** [comment]
> ![image](https://user-images.githubusercontent.com/61212989/137579662-b9c82ace-1bbb-4406-beb4-0cec16f25f79.png) anche con il plugin di ryuzakikk non si connette più (eppure si connetteva)... Raggiungo perfettamente la web UI della centrale via browser e via app (cloud) ed esegue tutti i comandi senza alcun problema. Sembra quasi che la porta 18034 dia problemi...

Se fai reboot della centrale dovrebbe funzionare, io faccio così quando si impalla: http://192.168.x.x/Reboot.htm

**Comment by Nik71git** [comment]
ehh l'ho fatto più volte... ho anche spento, tolto la connessione elettrica e riacceso (anche se in realtà ho lasciato collegata la batteria tampone...). Oggi provo a fare un reset ai valori di fabbrica. Confermi che la unica porta utilizzabile è la 18034?

**Comment by gideonklein** [comment]
> ehh l'ho fatto più volte... ho anche spento, tolto la connessione elettrica e riacceso (anche se in realtà ho lasciato collegata la batteria tampone...). Oggi provo a fare un reset ai valori di fabbrica. Confermi che la unica porta utilizzabile è la 18034?

Capisco. Ma giusto per curiosità, con il tuo flusso node-red tu riuscivi a vedere i PIR? Mi ricordo di aver letto che ne hai uno solo ma lo hai mai provato? Funziona? Voglio dire, ultimo evento lo riconosce di sicuro ma il sensore si attiva?

**Comment by Nik71git** [comment]
Allora, procediamo con ordine:
@maxill1 la mia centrale è una Siqura web di casasicura.it, usa una app propietaria che si appoggia al Cloud. Dal mio browser raggiungo tranquillamente la centrale via http. Ho il sospetto anch'io che l'addon sviluppato non chiuda bene la connessione perché rima con la versione web scraping e anche con quella di ryuzakikk funzionava benone. La controprova sarebbe uellà di eliminare il tuo addon, fare pulizia di tutti i payload con retain, riavviare la centrale ed installare solo il plugin di Ryuzakikk.
Il flusso node red andava bene ma al sensore PIR non veniva rilevato il cambio di stato a causa della rapidità on/off presumo.
@gideonklein: 
Webpage: 0.01F
Firmware: 0.03F 23 agosto 2015
Software: 1.53F_SIA_TCP  1 novembre 2018

**Comment by gideonklein** [comment]
> Allora, procediamo con ordine: @maxill1 la mia centrale è una Siqura web di casasicura.it, usa una app propietaria che si appoggia al Cloud. Dal mio browser raggiungo tranquillamente la centrale via http. Ho il sospetto anch'io che l'addon sviluppato non chiuda bene la connessione perché prima con la versione web scraping e anche con quella di ryuzakikk funzionava benone. La controprova sarebbe quella di eliminare il tuo addon, fare pulizia di tutti i payload con retain, riavviare la centrale ed installare solo il plugin di Ryuzakikk. Il flusso node red andava bene ma al sensore PIR non veniva rilevato il cambio di stato a causa della rapidità on/off presumo. @gideonklein: Webpage: 0.01F Firmware: 0.03F 23 agosto 2015 Software: 1.53F_SIA_TCP 1 novembre 2018

A me l'app proprietaria di casasicura non mi funziona da tempo e ne ho trovato altre 2 simili perfettamente funzionanti che uso entrambe. Allego gli screen
![1634393864525](https://user-images.githubusercontent.com/79428290/137591070-41f88c0a-886f-415f-b580-428af447a455.jpg)
![1634393864536](https://user-images.githubusercontent.com/79428290/137591091-771016d4-7883-49e9-b9ca-e2f28083b4ac.jpg)

**Comment by maxill1** [comment]
> Si confermo anche io che si blocca l'addon e non funziona niente neanche i sensori porte/finestre. Devo riavviare la centrale per sbloccare il tutto

ok per il blocco continuamo sull'issue dedicato:
https://github.com/maxill1/ialarm-mqtt/issues/23

**Comment by blakdog1978** [comment]
Ho reinstallato assistant pulito e fatto da capo ora l'integrazione non arriva oltre i 40 sensori dunque me ne restano fuori parecchi, nella prossima versione potresti fare in modo che siano 128 i sensori di defoult?
O mi potresti dire come settare le configurazioni per farlo in autonomia?
Non sono ancora riuscito a vedere se ora funzionano.
Grazie

**Comment by Salsalove** [comment]
> per la cronaca ho una siqura web di casasicura.it (Meian)

Ciao, scusa se riprendo una risposta di qualche mese fa...La centralina in tuo possesso è la Siqura WiFi monofrequenza?

Sono in procinto di acquistarne una da casasicura.it ma vorrei essere sicuro di poterla integrare in HA (so che quelle di ultima generazione non sono compatibili)

**Comment by maxill1** [comment]
> > per la cronaca ho una siqura web di casasicura.it (Meian)
> 
> Ciao, scusa se riprendo una risposta di qualche mese fa...La centralina in tuo possesso corrisponde con quella che adesso chiamano Siqura WiFi monofrequenza/doppia/quadrupla?
> 
> Sono in procinto di acquistarne una da casasicura.it ma vorrei essere sicuro di poterla integrare in HA (so che quelle di ultima generazione non sono compatibili)

Ciao, se devi prendere un antifurto con l'idea di integrarlo in HA prova a cercarne uno di quelli supportati ufficialmente: https://www.home-assistant.io/integrations/#alarm

queste centraline Meian (rebranded), al di la della loro bontà come antifurto su cui non so pronunciarmi, **non sono state pensate per integrarsi nativamente con il mondo esterno**. Io e altri possiamo anche sforzarci a scrivere codice, ma i protocolli non sono documentati, le centraline sebbene sembrino simili hanno comportamenti diversi tra loro e spesso è difficile darvi supporto.

Questo per dire che non dovresti scegliere l'antifurto in base all'esistenza o meno di un integrazione "non ufficiale" con un prodotto, perchè non potrei garantirti supporto a lungo termine ;)

**Comment by Salsalove** [comment]
> > > per la cronaca ho una siqura web di casasicura.it (Meian)
> 
> > 
> 
> > Ciao, scusa se riprendo una risposta di qualche mese fa...La centralina in tuo possesso corrisponde con quella che adesso chiamano Siqura WiFi monofrequenza/doppia/quadrupla?
> 
> > 
> 
> > Sono in procinto di acquistarne una da casasicura.it ma vorrei essere sicuro di poterla integrare in HA (so che quelle di ultima generazione non sono compatibili)
> 
> 
> 
> Ciao, se devi prendere un antifurto con l'idea di integrarlo in HA prova a cercarne uno di quelli supportati ufficialmente: https://www.home-assistant.io/integrations/#alarm
> 
> 
> 
> queste centraline Meian (rebranded), al di la della loro bontà come antifurto su cui non so pronunciarmi, **non sono state pensate per integrarsi nativamente con il mondo esterno**. Io e altri possiamo anche sforzarci a scrivere codice, ma i protocolli non sono documentati, le centraline sebbene sembrino simili hanno comportamenti diversi tra loro e spesso è difficile darvi supporto.
> 
> 
> 
> Questo per dire che non dovresti scegliere l'antifurto in base all'esistenza o meno di un integrazione "non ufficiale" con un prodotto, perchè non potrei garantirti supporto a lungo termine ;)


Ciao Luca, grazie per la risposta. Ho capito perfettamente ciò che dici.
Inizialmente mi ero orientato proprio verso un paio di antifurti che hanno l'integrazione ufficiale in HA, ma ad esempio, nel caso di ialarm ho poi letto (in ritardo) che non supporta le centraline XR e a quanto pare oggi vengono vendute solo centraline di quel tipo sul sito antifurto365.

Non potendo testare prima tutti gli altri marchi, non so davvero su quale orientarmi...anche perché, potrebbe succedere, come nel caso di iAlarm, che vengano rilasciate nuove centraline con diversi protocolli che poi comunque non funzionerebbero con le integrazioni ufficiali. 🤯

**Comment by maxill1** [comment]
> 
> Ciao Luca, grazie per la risposta. Ho capito perfettamente ciò che dici. Inizialmente mi ero orientato proprio verso un paio di antifurti che hanno l'integrazione ufficiale in HA, ma ad esempio, nel caso di ialarm ho poi letto (in ritardo) che non supporta le centraline XR e a quanto pare oggi vengono vendute solo centraline di quel tipo sul sito antifurto365.
> 
> Non potendo testare prima tutti gli altri marchi, non so davvero su quale orientarmi...anche perché, potrebbe succedere, come nel caso di iAlarm, che vengano rilasciate nuove centraline con diversi protocolli che poi comunque non funzionerebbero con le integrazioni ufficiali. exploding_head

Hai detto bene, purtroppo ora vendono solo la versione XR che non funziona ne con la mia integrazione ne con quella ufficiale basata su pyalarm.

Finche qualcuno non ci mette le mani su, sniffa il traffico di rete e vede cosa scambia la centralina con l'applicazione android non credo che le versioni XR saranno supportate da nessuno.

Tra l'altro qualche mese fa quelli di antifurto365 mi hanno mandato una mail per chiedermi di rendergli il vecchio in cambio dell'XR per pochi euro di differenza, ma non ho accettato. Quella nuova versione sembra supporti IFTTT e tramite quello google home e alexa, ma non ho altre info in merito e non ho garanzia che su rete locale si possa in qualche modo comunicare con la centrale.

Io ho un antifurto365 vecchio modello e finchè lo avrò continuerò a supportare quello in primis e tempo permettendo anche gli altri (purtroppo con risultati altalenanti)

Mi dispiace non poterti dare un consiglio chiaro.

**Comment by Salsalove** [comment]
> > 
> 
> > Ciao Luca, grazie per la risposta. Ho capito perfettamente ciò che dici. Inizialmente mi ero orientato proprio verso un paio di antifurti che hanno l'integrazione ufficiale in HA, ma ad esempio, nel caso di ialarm ho poi letto (in ritardo) che non supporta le centraline XR e a quanto pare oggi vengono vendute solo centraline di quel tipo sul sito antifurto365.
> 
> > 
> 
> > Non potendo testare prima tutti gli altri marchi, non so davvero su quale orientarmi...anche perché, potrebbe succedere, come nel caso di iAlarm, che vengano rilasciate nuove centraline con diversi protocolli che poi comunque non funzionerebbero con le integrazioni ufficiali. exploding_head
> 
> 
> 
> Hai detto bene, purtroppo ora vendono solo la versione XR che non funziona ne con la mia integrazione ne con quella ufficiale basata su pyalarm.
> 
> 
> 
> Finche qualcuno non ci mette le mani su, sniffa il traffico di rete e vede cosa scambia la centralina con l'applicazione android non credo che le versioni XR saranno supportate da nessuno.
> 
> 
> 
> Tra l'altro qualche mese fa quelli di antifurto365 mi hanno mandato una mail per chiedermi di rendergli il vecchio in cambio dell'XR per pochi euro di differenza, ma non ho accettato. Quella nuova versione sembra supporti IFTTT e tramite quello google home e alexa, ma non ho altre info in merito e non ho garanzia che su rete locale si possa in qualche modo comunicare con la centrale.
> 
> 
> 
> Io ho un antifurto365 vecchio modello e finchè lo avrò continuerò a supportare quello in primis e tempo permettendo anche gli altri (purtroppo con risultati altalenanti)
> 
> 
> 
> Mi dispiace non poterti dare un consiglio chiaro.


Grazie comunque per i tuoi chiarimenti e buon lavoro!

**Comment by maxill1** [comment]
Chiudo per fare un po di pulizia. Se avete bug specifici apritene di nuovi o se pertinente accodatevi a quelli aperti.

**Comment by Salsalove** [comment]
Io non ho capito cosa sta succedendo con gli aggiornamenti...2.0.8 qualche giorno fa e oggi mi è uscita la versione 0.10.1

**Comment by maxill1** [comment]
> Io non ho capito cosa sta succedendo con gli aggiornamenti...2.0.8 qualche giorno fa e oggi mi è uscita la versione 0.10.1

**spiegato qui:**
- https://github.com/maxill1/ialarm-mqtt/issues/23#issuecomment-1312465813
- https://github.com/maxill1/ialarm-mqtt/issues/36#issuecomment-1312454179
- e sul readme dell'addon stesso https://github.com/maxill1/addons/blob/master/ialarm-mqtt/README.md
