### ISSUE TITLE
Wired sensor support

### ISSUE THREAD

**Issue by maxill1** [maxill1/ialarm-mqtt#19]
Buongiorno,
mi unisco anch'io con la versione tpc sembra funzionare mi crea i sensori e i baypass di zona, solo che i contatti sulle porte che sono sensori filari me li da sempre chiusi, e i rilevatori di movimento esterni me li da sempre aperti, cosa devo fare ? E ancora quando provo ad armare mi arma sempre la zona 1 e non le altre ...

_Originally posted by @blakdog1978 in https://github.com/maxill1/ialarm-mqtt/issues/18#issuecomment-940846908_

**Comment by maxill1** [comment]
secondo me qualcosa non va con il numero di zona:
Nome "Zona 36" mentre:
```
id: 10
zone: 10
typeId: 0
type: Disabilitata
```
Sopratutto dice che questa "zona 36", e che ha ha id 10, è una zona disabilitata (typeId = 0).

Hai una zona 10 che effettivamente non è configurata e risulta disabilitata dal tuo pannello?

Per me questo problema è correlabile all'errore sui numeri zona sbagliati che mi segnalava @gideonklein

**Comment by gideonklein** [comment]
Sarebbe grande

**Comment by blakdog1978** [comment]
Provando ad armare con custom bypass si è chiuso addon e nel registro c'è questo:

received topic 'ialarm/alarm/set' :  ARM_CUSTOM_BYPASS
Alarm command: ARM_CUSTOM_BYPASS (ARM_CUSTOM_BYPASS)
/app/node_modules/ialarm-mqtt/index.js:194
        if (!commandType || !alarm[commandType]()) {
                                               ^
TypeError: alarm[commandType] is not a function
    at Object.armDisarm (/app/node_modules/ialarm-mqtt/index.js:194:48)
    at MqttClient.<anonymous> (/app/node_modules/ialarm-mqtt/utils/mqtt-publisher.js:213:35)
    at MqttClient.emit (events.js:198:13)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:410:12)
    at work (/app/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:307:11)
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by maxill1** [comment]
> l'ho fatto da lovelace ...

```yaml
ok per ora vi consiglio di configurare la card di lovelace con i soli stati gestiti:
type: alarm-panel
states:
  - arm_home
  - arm_away
entity: alarm_control_panel.ialarm
```
per armed_custom_bypass non credo che l'allarme lo supporti di suo, si potrebbe creare un comando ad hoc che arma e poi fa il bypass di zone specifiche (configurabili da yaml magari), ma per ora non je la faccio a farlo, prima rendiamolo stabile :smile:

**Comment by blakdog1978** [comment]
L'ho fatto solo per provare magari andava ad armare aree diverse dalla 1, non saprei neppure io come usare quel comando ...

**Comment by maxill1** [comment]
La centrale ha uno schermo? Sulla mia quando apro una porta o finestre appare:
F-01 dove F è fault e 01 è la zona 1.

Se mi muovo in casa con i PIR non vedo nulla sulla centrale. Secondo me quei sensori riportano nulla se non usando sono allarmati e quindi:
A-02 dove a è allarme e 02 e la zona 2.

Non so che dirvi riguardo i 24 ore, a me funziona riporta aperto (perché è un sensore normalmente aperto) 😞
