### ISSUE TITLE
Alarm triggered not reporting status

### ISSUE THREAD

**Issue by maxill1** [maxill1/ialarm-mqtt#21]
If armed/armed home and triggered the status is still armed/armed home and not "triggered"

_Originally posted by @mrMiimo in https://github.com/maxill1/ialarm-mqtt/issues/17#issuecomment-944171670_

**Comment by maxill1** [comment]
fixed in node-ialarm@0.4.5 and will be included in next ialarm-mqtt version

**Comment by mrMiimo** [comment]
I think something is missing, when I do "docker-compose pull" it does not download anything ...
