### ISSUE TITLE
PIR Sensor not reporting "fault" on activation

### ISSUE THREAD

**Issue by maxill1** [maxill1/ialarm-mqtt#22]
Sensori porte e finestre sono perfettamente funzionanti e in 5 secondi rilevano lo stato anche last event è coerente
- I sensori PIR e i sensori acqua, gas e fumo non si attivano proprio neanche su last event. Da tenere presente che i PIR si attivano con la centrale armata (che funziona) 

_Originally posted by @gideonklein in https://github.com/maxill1/ialarm-mqtt/issues/19#issuecomment-943100863_

**Comment by maxill1** [comment]
confermo che se la centrale è attivata i PIR riportano "alarm" mentre se disattivata il "fault" (che dovrebbe identificare il movimento) non viene mai osservato ne su node-ialarm ne sulla centrale fisicamente:

Riporto quanto detto in un altro issue https://github.com/maxill1/ialarm-mqtt/issues/19#issuecomment-943530788 

Ad antifurto disarmato, se apro una finestra o porta (sensori a contatto) che è associata alla zona 1, sullo schermo del mio antifurto appare:
**F-01** 
dove F è fault e 01 è la zona 1.

Ad antifurto armato, se apro una finestra o porta (sensori a contatto) che è associata alla zona 1, sullo schermo del mio antifurto appare:
**A-01** 
dove A è fault e 01 è la zona 1.

Ad antifurto disarmato, se mi muovo vicino ad un PIR che è associato ad una zona 2, questo lampeggia per dirmi che mi vede ma sullo schermo del mio antifurto non **appare nulla**

Ad antifurto armato,  se mi muovo vicino ad un PIR che è associato ad una zona 2, questo lampeggia per dirmi che mi vede e sullo schermo del mio antifurto appare:
**A-02** 
dove A è fault e 02 è la zona 2.

Stessa cosa ma in forma diversa appare sul pannello web, quindi **se la centrale non lo vede, non può neanche node-ialarm/ialarm-mqtt**.

Fate le stesse prove e fatemi sapere.

![image](https://user-images.githubusercontent.com/367042/137500346-efcebca3-22d0-42f2-a7e2-5873472c3e20.png)


P.S.

**Comment by gideonklein** [comment]
Ma una curiosità, dato che abbiamo la centralina identica (anche se estetica diversa) a te funzionano i PIR?
In ogni caso dobbiamo rinunciarci a questo addon o in futuro forse si potrà utilizzare?

**Comment by maxill1** [comment]
No, come dicevamo ieri i PIR a me, come a voi, riportano solo se armata la centrale altrimenti non riportano...

Per quanto riguarda l'utilizzo dell'addon sto correggendo quello che mi segnalate e che riesco riprodurre, appena possibile rilascio tutto.

**Comment by gideonklein** [comment]
> No, come dicevamo ieri i PIR a me, come a voi, riportano solo se armata la centrale altrimenti non riportano...
> 
> Per quanto riguarda l'utilizzo dell'addon sto correggendo quello che mi segnalate e che riesco riprodurre, appena possibile rilascio tutto.

Ah bene allora aspetto. Comunque a me i PIR non funzionano nemmeno a centrale armata (che funziona). Vedremo che succede  nella prossima versione. Grazie come sempre
