### ISSUE TITLE
iAlarm XR-5

### ISSUE THREAD

**Issue by Salsalove** [maxill1/ialarm-mqtt#26]
Non si tratta di un "problema" ma di una domanda ben specifica. 
Questo add-on è compatibile con la centralina iAlarm XR-5 (o anche XR-2 o XR-3)?

**Comment by maxill1** [comment]
no sorry. Protocol may differ, see here:
https://github.com/RyuzakiKK/pyialarm/issues/6

**Comment by Salsalove** [comment]
Quale centralina di Casasicura è invece compatibile con questo addio-on? Siqura WiFi Monofrequenza lo è?
