### ISSUE TITLE
Compatibilità WMG Defcon 9 - FOCUS FC7664Pro_V2.0

### ISSUE THREAD

**Issue by dariob84** [maxill1/ialarm-mqtt#32]
Ciao,
ho provato ad utilizzare il componente con la nuova centrale DEFCON 9 (FC7664Pro_V2.0) ma purtroppo senza successo. Qualcuno è riuscito ad integrarla?

Info. sistema
Versione pagina WEB
Web-V1.05
Versione audio
Audio-SKY-ITA_V1.0
Versione Hardware
FC7664Pro_V2.0
Versione Firmware
STD-EN_V1.02 ASK/868 Dec 17 2021

avviando il componente ho il seguente log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:44:06] INFO: Passing /data/options.json to ialarm-mqtt@ 0.10.1 with node-ialarm@ 0.5.1
Found arg --hassos with value /data/options.json
info: Trying to merge HASSOS options file (/data/options.json) with default config.json
warning: Config.json value not specified on /data/options.json using default '' on ["name"]
info: Starting up...
info: MQTT connecting to broker 192.168.1.126:1883 with cliendId ialarm-mqtt
info: MQTT connected to broker 192.168.1.126:1883 with cliendId ialarm-mqtt
info: subscribing to ["ialarm/alarm/discovery","ialarm/alarm/resetCache","ialarm/alarm/area/+/set","ialarm/alarm/zone/+/bypass"]
info: Setting up first TCP connection to retrieve mac address...
"GetNet": concurrent commands, delaying 200ms
error: 397-["GetNet"] tcp socket timeout
error: 397-["GetNet"]: throw an error: 397-["GetNet"] tcp socket timeout {"stack":"Error: 397-[\"GetNet\"] tcp socket timeout\n    at Socket.socket.on (/app/ialarm-mqtt/node_modules/ialarm/src/meian-socket.js:135:18)\n    at Socket.emit (events.js:198:13)\n    at Socket._onTimeout (net.js:443:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}
error: Error starting up: 397-["GetNet"] tcp socket timeout
info: Stopping...
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

GRAZIE

**Comment by maxill1** [comment]
Ciao, va in timeout sul socket di connessione quindi ipotizzo potenziali cause:
- l'indirizzo IP che hai inserito sulla configurazione di ialarm-mqtt è sbagliato e quindi non raggiungi la centrale (deve essere lo stesso da cui vai da web)
- la porta TCP utilizzata per quel modello (FC7664Pro) è diversa
- il tuo modello non espone via TCP I dati ma solo da Cloud e con qualche sensibile variazione al protocollo (vedi le centrali nuove di antofurto364)
- ialarm-mqtt e la centrale non sono sulla stessa rete/sotto rete

Come si chiama l'applicazione android con cui ti connetti? Spesso queste centrali hanno applicazioni gemelle intercambiabili tra loro, ad esempio se provi SP-Panel da Android e ti colleghi con gli stessi settaggi della tua applicazione originale, molto probabilmente la centrale è compatibile con ialarm-mqtt, altrimenti no.

**Comment by dariob84** [comment]
- l'indirizzo IP è corretto e a differenza dei modelli precedenti ha come indirizzo di default 192.168.1.200 (vecchi modelli .81);

- la porta TCP utilizzata per quel modello (FC7664Pro) è diversa - Purtoppo non è poossibile conoscere la porta, le impostazioni del cms sono tutte vuote, infatti l'inserimento della centrale nell'app avviene tramite qrcode;
- Come si chiama l'applicazione android con cui ti connetti?  - l'app che ti dicono di scaricare è SmartSecurity, e non posso aggiungere la centrale nella vecchia app ST PANEL EX perché non conosco l'indirizzo del server e la porta.

**Comment by maxill1** [comment]
È questa? https://play.google.com/store/apps/details?id=com.smartdefense

**Comment by dariob84** [comment]
Si

Il ven 7 ott 2022, 20:05 Luca Mazzilli ***@***.***> ha
scritto:

**Comment by maxill1** [comment]
Andrebbe sniffato il traffico per esserne certi, ma il fatto che quell'app non faccia configurare nulla oltre username e password mi fa credere che la centrale non esponga nulla su rete locale e vada sul cloud come le nuove iAlarm XR. C'era un progetto per quelle centrali, ora fatto chiudere, che passando per il loro Cloud integrava in home assistant, magari con quello funziona. Mi dispiace.

**Comment by dariob84** [comment]
Grazie per il tuo supporto. Ho effettuato una scansione delle porte e ho
visto che comunica con la porta 8000. Quindi ho modificato le impostazioni
del componente e tutto funziona. Grazie mille

Il ven 7 ott 2022, 20:19 Luca Mazzilli ***@***.***> ha
scritto:

**Comment by maxill1** [comment]
questa è una buona notizia!
