### ISSUE TITLE
Siqura JX

### ISSUE THREAD

**Issue by grampasso-lento** [maxill1/ialarm-mqtt#33]
Salve a tutti,
Possiedo un Casasicura Siqura JX. Ho verificato con un tool che la sola porta aperta è la 6668.
Ho installato il tuo add-on e l'ho configurato prima con la porta 18034 e poi con 6668. Ti allego i log.
Naturalmente per la prima viene negata la connessione.
Suggerimenti?
Grazie mille
Giovanni

PORTA 18034 --------------------------------------------------
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:51:36] INFO: Passing /data/options.json to ialarm-mqtt@ 0.10.1 with node-ialarm@ 0.5.1
Found arg --hassos with value /data/options.json
info: Trying to merge HASSOS options file (/data/options.json) with default config.json
info: Starting up...
info: MQTT connecting to broker 192.168.1.5:1883 with cliendId ialarm-mqtt
info: MQTT connected to broker 192.168.1.5:1883 with cliendId ialarm-mqtt
info: subscribing to ["ialarm/alarm/discovery","ialarm/alarm/resetCache","ialarm/alarm/area/+/set","ialarm/alarm/zone/+/bypass"]
info: Setting up first TCP connection to retrieve mac address...
"GetNet": concurrent commands, delaying 200ms
error: 2341-["GetNet"]: error connect ECONNREFUSED 192.168.20.250:18034
error: 2341-["GetNet"]: throw an error: connect ECONNREFUSED 192.168.20.250:18034 {"address":"192.168.20.250","code":"ECONNREFUSED","errno":"ECONNREFUSED","port":18034,"stack":"Error: connect ECONNREFUSED 192.168.20.250:18034\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)","syscall":"connect"}
error: Error starting up: connect ECONNREFUSED 192.168.20.250:18034
info: Stopping...
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

PORTA 6668 --------------------------------------------------

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:56:31] INFO: Passing /data/options.json to ialarm-mqtt@ 0.10.1 with node-ialarm@ 0.5.1
Found arg --hassos with value /data/options.json
info: Trying to merge HASSOS options file (/data/options.json) with default config.json
info: Starting up...
info: MQTT connecting to broker 192.168.1.5:1883 with cliendId ialarm-mqtt
info: MQTT connected to broker 192.168.1.5:1883 with cliendId ialarm-mqtt
info: subscribing to ["ialarm/alarm/discovery","ialarm/alarm/resetCache","ialarm/alarm/area/+/set","ialarm/alarm/zone/+/bypass"]
info: Setting up first TCP connection to retrieve mac address...
"GetNet": concurrent commands, delaying 200ms
error: 6304-["GetNet"] tcp socket timeout
error: 6304-["GetNet"]: throw an error: 6304-["GetNet"] tcp socket timeout {"stack":"Error: 6304-[\"GetNet\"] tcp socket timeout\n    at Socket.socket.on (/app/ialarm-mqtt/node_modules/ialarm/src/meian-socket.js:135:18)\n    at Socket.emit (events.js:198:13)\n    at Socket._onTimeout (net.js:443:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}
error: Error starting up: 6304-["GetNet"] tcp socket timeout
info: Stopping...
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by maxill1** [comment]
credo che valgano le stesse considerazioni fatte per[ FOCUS FC7664Pro](https://github.com/maxill1/ialarm-mqtt/issues/32): probabilmente si tratta di una centrale che al pari di iAlarm XR espone tutto tramite cloud e non su TCP locale.
