### ISSUE TITLE
sensor.ialarm_comunication_error won't reset itself

### ISSUE THREAD

**Issue by maxill1** [maxill1/ialarm-mqtt#34]
sensor.ialarm_comunication_error value should reset if connection is OK.

switch.ialarm_clean_cache should also reset sensor.ialarm_comunication_error.

![image](https://user-images.githubusercontent.com/367042/198289268-e208baa9-524c-4d8e-b112-2a3b8118eed9.png)

_Originally posted by @maxill1 in https://github.com/maxill1/ialarm-mqtt/issues/23#issuecomment-1293485579_

**Comment by sdavides** [comment]
Ok, si può mettere aggiungere/aggiustare questa configurazione da qualche file?
Io non ho lo switch come indicato nel link, ma on e off, qale dove fare?

![immagine](https://user-images.githubusercontent.com/31100253/198293443-147add94-2c60-431b-a7b0-1791a41d04f5.png)

**Comment by maxill1** [comment]
> Ok, si può mettere aggiungere/aggiustare questa configurazione da qualche file? Io non ho lo switch come indicato nel link, ma on e off, qale dove fare?
> 
> ![immagine](https://user-images.githubusercontent.com/31100253/198293443-147add94-2c60-431b-a7b0-1791a41d04f5.png)

Quella rappresentazione dipende da home assistant che disegna gli switch [MQTT ](https://www.home-assistant.io/integrations/switch.mqtt)(e altri) in base alla predicibilità dello stato (assumed_state). Sono la stessa identica cosa, solo che "in quel momento" home assistant non sa se sono "on" o "off" e quindi li disegna con due pulsanti invece che un toggle. 

Probabilmente non hai ancora ricevuto un messaggio MQTT che chiarisce ad HA quale stato abbiano quegli switches.

**Comment by maxill1** [comment]
Corretto nella versione dev (0.11.x): creato un binary_sensor di stato che si aggiorna a "OK" dopo che la connessione torna a dare risposte buone a GetAlarmStatus o GetArea
