### ISSUE TITLE
Update to version 2.0.8 failed - > fallback to 0.10.1 (stable)

### ISSUE THREAD

**Issue by blakdog1978** [maxill1/ialarm-mqtt#36]
Buongiorno, sto provando ad aggiornare all'ultima versione ma mi da questo errore:

`Can't install c94950d3/aarch64-addon-ialarm-mqtt:2.0.8: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.0.8&fromImage=c94950d3%2Faarch64-addon-ialarm-mqtt&platform=linux%2Farm64: Not Found ("pull access denied for c94950d3/aarch64-addon-ialarm-mqtt, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")`

**Comment by maxill1** [comment]
le actions di generazione delle immagini falliscono, evidentemente qualcosa è cambiato lato action e sto provando a capire cosa non va. Per ora non aggiornate.

https://github.com/maxill1/addons/actions

**Comment by blakdog1978** [comment]
OK grazie

**Comment by blakdog1978** [comment]
ora si aggiorna ma non va...

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:41:58] INFO: Passing /data/options.json to ialarm-mqtt@ 0.11.0 with node-ialarm@ 0.6.0
/app/ialarm-mqtt/bin/ialarm-mqtt.js:2
import { ialarmMqtt } from '../index.js'
       ^
SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by maxill1** [comment]
[Corretta](https://github.com/maxill1/addons/issues/2
), aggiornate alla 2.0.8bis e dovrebbe avviarsi.

Per il futuro ho fatto due versioni dell'addon, una stabile e una dev, cosi potete passare da una all'altra senza rompere l'installazione principale.

![image](https://user-images.githubusercontent.com/367042/201449507-1cb0d5e2-7316-4b03-b179-d2c49280fc92.png)

**Comment by blakdog1978** [comment]
Per info ... ho provato la nuova versione stabile, ma a me non funziona non aggiorna lo stato ei sensori, sembra non trovarli neanche tutti ... li da tutti chiusi e non riconosce neanche lo stato della centrale,
ecco il log.

`info: Retrieving zone info ...
info: Caching ialarm/alarm/availability until Sat Nov 12 2022 08:49:29 GMT+0100 (Central European Standard Time)
info: Status polling every 3000ms
info: A request is in progress...we will wait for response before sending "GetZone" (undefined)
info: A request is in progress...we will wait for response before sending "GetZone" (undefined)
info: A request is in progress...we will wait for response before sending "GetZone" (undefined)
info: A request is in progress...we will wait for response before sending "GetZone" (undefined)
info: A request is in progress...we will wait for response before sending "GetZone" (undefined)
info: A request is in progress...we will wait for response before sending "GetZone" (undefined)
info: A request is in progress...we will wait for response before sending "GetZone" (undefined)
info: A request is in progress...we will wait for response before sending "GetZone" (undefined)
info: A request is in progress...we will wait for response before sending "GetZone" (undefined)
info: A request is in progress...we will wait for response before sending "GetZone" (undefined)
info: got 2 ' zones info'
info: removeDisabledZones: filtering out zone 1 with typeId disabled {"id":1,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":1}
info: removeDisabledZones: filtering out zone 2 with typeId disabled {"id":2,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":2}
info: Caching ialarm/alarm/configStatus until Sat Nov 12 2022 08:49:29 GMT+0100 (Central European Standard Time)
info: sending topic 'homeassistant/alarm_control_panel/ialarm/config' : 
info: sending topic 'homeassistant/sensor/ialarm/error/config' : 
info: Caching ialarm/alarm/error until Sat Nov 12 2022 08:49:29 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/alarm/error' : 
info: sending topic 'homeassistant/switch/ialarm/clear_cache/config' : 
info: sending topic 'homeassistant/switch/ialarm/clear_discovery/config' : 
info: sending topic 'homeassistant/binary_sensor/ialarm/connection/config' : 
info: sending topic 'homeassistant/switch/ialarm/clear_triggered/config' : 
info: sending topic 'homeassistant/alarm_control_panel/ialarm_1/config' : 
info: sending topic 'homeassistant/alarm_control_panel/ialarm_2/config' : 
info: sending topic 'homeassistant/alarm_control_panel/ialarm_3/config' : 
info: sending topic 'homeassistant/alarm_control_panel/ialarm_4/config' : 
info: sending topic 'homeassistant/sensor/ialarm/events/config' : 
info: Setting up Home assistant discovery...
info: got 2 ' zones info'
info: removeDisabledZones: filtering out zone 1 with typeId disabled {"id":1,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":1}
info: removeDisabledZones: filtering out zone 2 with typeId disabled {"id":2,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":2}
error: error status.toLowerCase is not a function
info: Caching ialarm/alarm/state until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/alarm/state' : Object with 1 keys
info: Caching ialarm/sensors/state until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/state' : Array of 16 elements
info: Caching ialarm/sensors/zone_1 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_1' : Object with 17 keys
info: Caching ialarm/sensors/zone_2 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_2' : Object with 17 keys
info: Caching ialarm/sensors/zone_3 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_3' : Object with 12 keys
info: Caching ialarm/sensors/zone_4 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_4' : Object with 12 keys
info: Caching ialarm/sensors/zone_5 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_5' : Object with 12 keys
info: Caching ialarm/sensors/zone_6 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_6' : Object with 12 keys
info: Caching ialarm/sensors/zone_7 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_7' : Object with 12 keys
info: Caching ialarm/sensors/zone_8 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_8' : Object with 12 keys
info: Caching ialarm/sensors/zone_9 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_9' : Object with 12 keys
info: Caching ialarm/sensors/zone_10 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_10' : Object with 12 keys
info: Caching ialarm/sensors/zone_11 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_11' : Object with 12 keys
info: Caching ialarm/sensors/zone_12 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_12' : Object with 12 keys
info: Caching ialarm/sensors/zone_13 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_13' : Object with 12 keys
info: Caching ialarm/sensors/zone_14 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_14' : Object with 12 keys
info: Caching ialarm/sensors/zone_15 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_15' : Object with 12 keys
info: Caching ialarm/sensors/zone_16 until Sat Nov 12 2022 08:49:32 GMT+0100 (Central European Standard Time)
info: sending topic 'ialarm/sensors/zone_16' : Object with 12 keys
warning: Feature events is disabled
info: sending topic 'homeassistant/switch/ialarm/clear_cache/config' : Object with 11 keys
info: sending topic 'homeassistant/switch/ialarm/clear_discovery/config' : Object with 11 keys
info: sending topic 'homeassistant/binary_sensor/ialarm/connection/config' : Object with 12 keys
info: sending topic 'homeassistant/switch/ialarm/clear_triggered/config' : Object with 11 keys
info: sending topic 'homeassistant/alarm_control_panel/ialarm_1/config' : Object with 13 keys
info: sending topic 'homeassistant/alarm_control_panel/ialarm_2/config' : Object with 13 keys
info: sending topic 'homeassistant/alarm_control_panel/ialarm_3/config' : Object with 13 keys
info: sending topic 'homeassistant/alarm_control_panel/ialarm_4/config' : Object with 13 keys
info: got 2 ' zones info'
info: removeDisabledZones: filtering out zone 1 with typeId disabled {"id":1,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":1}
info: removeDisabledZones: filtering out zone 2 with typeId disabled {"id":2,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":2}
error: error status.toLowerCase is not a function
info: got 2 ' zones info'
info: removeDisabledZones: filtering out zone 1 with typeId disabled {"id":1,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":1}
info: removeDisabledZones: filtering out zone 2 with typeId disabled {"id":2,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":2}
error: error status.toLowerCase is not a function
info: got 2 ' zones info'
info: removeDisabledZones: filtering out zone 1 with typeId disabled {"id":1,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":1}
info: removeDisabledZones: filtering out zone 2 with typeId disabled {"id":2,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":2}
error: error status.toLowerCase is not a function
info: got 2 ' zones info'
info: removeDisabledZones: filtering out zone 1 with typeId disabled {"id":1,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":1}
info: removeDisabledZones: filtering out zone 2 with typeId disabled {"id":2,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":2}
error: error status.toLowerCase is not a function
info: got 2 ' zones info'
info: removeDisabledZones: filtering out zone 1 with typeId disabled {"id":1,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":1}
info: removeDisabledZones: filtering out zone 2 with typeId disabled {"id":2,"name":"","type":"Disabilitata","typeId":0,"voiceId":2,"voiceName":"Ad impulsi","zone":2}
error: error status.toLowerCase is not a function`

![centrale](https://user-images.githubusercontent.com/36457031/201464506-206fee39-be9a-4ca1-b6e6-952febc7e05b.JPG)

**Comment by maxill1** [comment]
ho ripristinato la versione stabile dell'addon a ialarm-mqtt 0.10.1 (in pratica la versione 2.0.7 dell'addon).
Da questo momento allineerò i nomi di versione tra ialarm-mqtt e relativo addon per rendere più chiaro cosa stiamo eseguendo.

Ciao
