### ISSUE TITLE
Hello I have add code on my configuration below hadiscovery.

### ISSUE THREAD

**Issue by maxill1** [maxill1/ialarm-mqtt#40]
Hello I have add code on my configuration below hadiscovery.
but not working why?
![image](https://user-images.githubusercontent.com/31816231/202390595-dce5f444-9799-418b-bd8f-669ae58b5f1a.png)
![image](https://user-images.githubusercontent.com/31816231/202390648-359d52ae-e3f2-4328-927d-70610b25f13a.png)

_Originally posted by @wifi75 in https://github.com/maxill1/ialarm-mqtt/discussions/39_

**Comment by maxill1** [comment]
@gideonklein @wifi75 dovrebbe essere risolto nell'attuale versione dell'addon "dev-08b3c80"

**Comment by gideonklein** [comment]
Grazie, ottimo lavoro

**Comment by wifi75** [comment]
ciao ma io non ho installato la versione Dev.... ho la versione normale.... che devo fare?

**Comment by maxill1** [comment]
Puoi installare la versione dev e provare le modifiche (ialarm-mqtt-dev) oppure attendere che queste correzioni le riporto sulla stabile dove sei.

**Comment by wifi75** [comment]
ciao ho installato questa versione
![image](https://user-images.githubusercontent.com/31816231/204084349-cd3cfdce-461e-45b1-86de-840d536f888d.png)

aggiungendo code: 1875
![image](https://user-images.githubusercontent.com/31816231/204084374-432bc763-12ad-48d7-a293-18fa05d53978.png)

continua a non mostrare la tastiera.

![image](https://user-images.githubusercontent.com/31816231/204084398-a16ed1de-4099-4209-b49a-d1c3f8dd6f59.png)

**Comment by gideonklein** [comment]
evi metterlo su HAdiscovery:
alarm_qos: 2
sensors_qos: 0
zoneName: Zone
code: 1234

**Comment by wifi75** [comment]
si funziona, grazie
