### ISSUE TITLE
[bug]: Individuate entità MQTT con un nome uguale al nome del dispositivo

### ISSUE THREAD

**Issue by Donez84** [maxill1/ialarm-mqtt#50]
### Version

0.10.1 (Default)

### What happened?

Alcune entità MQTT hanno un nome di entità uguale al nome del dispositivo. Questo non è previsto. Il nome dell'entità è impostato su null come soluzione per evitare un nome duplicato. Si prega di informare il manutentore dell'applicazione software che fornisce le entità interessate per risolvere questo problema.

Elenco delle entità interessate:

binary_sensor.alarm_zone_29
binary_sensor.alarm_zone_19
binary_sensor.alarm_zone_26
binary_sensor.alarm_zone_22
binary_sensor.alarm_zone_21
binary_sensor.alarm_zone_4_o_pt_letto
binary_sensor.alarm_zone_5_pt_cantina
binary_sensor.alarm_zone_13
binary_sensor.alarm_zone_16
alarm_control_panel.alarm
binary_sensor.alarm_zone_6_s_pt_salotto
binary_sensor.alarm_zone_8
binary_sensor.alarm_zone_24
binary_sensor.alarm_zone_25
binary_sensor.alarm_zone_14
binary_sensor.alarm_zone_20
binary_sensor.alarm_zone_23
binary_sensor.alarm_zone_2_o_pt_scale_uff
binary_sensor.alarm_zone_28
binary_sensor.alarm_zone_18
binary_sensor.alarm_zone_7_e_pt_palestra
binary_sensor.alarm_zone_11
binary_sensor.alarm_zone_27
binary_sensor.alarm_zone_32
binary_sensor.alarm_zone_1
binary_sensor.alarm_zone_12
binary_sensor.alarm_zone_15
binary_sensor.alarm_zone_17
binary_sensor.alarm_zone_3_n_pt_portico
binary_sensor.alarm_zone_9
binary_sensor.alarm_zone_10
binary_sensor.alarm_zone_31
binary_sensor.alarm_zone_30

Questo smette di funzionare nella versione 2024.2.0. Risolvi il problema prima di effettuare l'aggiornamento.

### Where are you running ialarm-mqtt?

Hass.io addon

### Alarm panel model

antifurto365

**Comment by maxill1** [comment]
Duplicate https://github.com/maxill1/ialarm-mqtt/issues/51

C'è n'era una identica sul repo dell'addon, l'ho trasferita
