### ISSUE TITLE
Homeassistant discovery not working

### ISSUE THREAD

**Issue by eogmau** [maxill1/ialarm-mqtt#6]
Hi @maxill1 , thanks for your great work.
Homeassistant discovery is not working for me, below is a snipped of the container log.
`Home assistant discovery disabled (empty config.hadiscovery)
connected...
subscribing to ["ialarm/alarm/set","ialarm/alarm/zone/+/bypass","ialarm/alarm/discovery"]
Creating new iAlarm connection`

Looking at index.js [discovery function](https://github.com/maxill1/ialarm-mqtt/blob/efd86f893d5f18996b4d048caab90f2dbf7fa345/index.js#L249) can see 
` if(!enabled){
            console.log("Home assistant discovery disabled (empty config.hadiscovery)");
        }`

I am using the config you have provided and didn't change the hadiscovery part.

**Comment by eogmau** [comment]
Hello, me again.
Managed to sort the autodiscovery part, have added `"enabled" : "true"` in config to the hadiscovery.
Code looks good from your side, big respect,
Can see a bit of delay in binary sensors.

**Comment by maxill1** [comment]
Thank you eogmau.

I managed to add the binary sensors with the help of great tester but what we can "sense" is limited to what you can observe in the alarm web panel. You can try to reduce the status polling to find the right value for you (default is 30000 milliseconds - 30 seconds):

`
"polling" : {
            "status" : 30000,
            "events" : 10000
        }
`

**Comment by eogmau** [comment]
Have configured the pooling for 10 seconds, which I think its still too long, when watching the sensor in the web panel they are very quick to appear and disappear, probably pooling of 1 second will be just right but we are hammering the alarm panel with requests.
Someone managed to reverse engineer the meian (ialarm) protocol where you can subscribe to the MeianPushClient where the alarm will send all the events/alarms to homeassistant without us hammering the web panel. 
https://github.com/wildstray/meian-client/wiki

**Comment by maxill1** [comment]
@eogmau  anyway, I've been playing with wildtray/meian-client a little and I think I try to rewrite it in node.js as a drop in replacement of the current html scraper node-ialarm (not sure when).

**Comment by eogmau** [comment]
Thanks @maxill1 , hope you find time for this 👍 .
Were you able to run the meian-client python script?
I am trying to run it with python but I am unable, throwing connection error.

**Comment by maxill1** [comment]
Yes, I managed to run the script by editing line 639.

Here the details: https://github.com/wildstray/meian-client/issues/1#issuecomment-616083069

**Comment by stezak77** [comment]
@maxill1 if you manage to re-engineer your software using wildtray/meian-client, I volounteer for some testing

**Comment by maxill1** [comment]
@stezak77  few weeks ago I wrote the core of the TCP implementation in [node-ialarm](https://github.com/maxill1/node-ialarm) using wildstray [wiki](https://github.com/wildstray/meian-client/wiki).

let's continue here:
https://github.com/maxill1/node-ialarm/issues/2#issue-617259995
